title = "Anagha Premkumar"
# determines default content language ["en", "zh-cn", "fr", "pl", ...]
defaultContentLanguage = "en"
# language code ["en", "zh-CN", "fr", "pl", ...]
languageCode = "en"

# Change the default theme to be use when building the site with Hugo
theme = "FixIt"

[params]
  # FixIt theme version
  version = "0.2.18"
  # site description
  description = "A curated collection of cherished memories here at my corner in cyberspace "
  # site default theme ["light", "dark", "auto"]
  defaultTheme = "auto"
  # public git repo url only then enableGitInfo is true
  enableFitInfo = true
  gitRepo = "https://github.com/anu-doc/anu-doc.github.io"
  # FixIt 0.1.1 | NEW which hash function used for SRI, when empty, no SRI is used
  # ["sha256", "sha384", "sha512", "md5"]
  fingerprint = ""
  # FixIt 0.2.0 | NEW date format
  dateFormat = "2006-01-02"
  # website images for Open Graph and Twitter Cards
  images = ["/images/avatar.png"]
  # FixIt 0.2.12 | NEW enable PWA
  enablePWA = true
  # FixIt 0.2.14 | NEW whether to add external Icon for external links automatically
  externalIcon = true
  # FixIt 0.2.14 | NEW FixIt will, by default, inject a theme meta tag in the HTML head on the home page only.
  # You can turn it off, but we would really appreciate if you don’t, as this is a good way to watch FixIt's popularity on the rise.
  disableThemeInject = false
[params.header]
    # FixIt 0.2.13 | CHANGED desktop header mode ["sticky", "normal", "auto"]
    desktopMode = "sticky"
    # FixIt 0.2.13 | CHANGED mobile header mode ["sticky", "normal", "auto"]
    mobileMode = "auto"
    # FixIt 0.2.0 | NEW Header title config
    [params.header.title]
      # URL of the LOGO
      logo = "/images/avatar.png"
      # title name
      name = "Anagha Sheeja Premkumar"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      # FixIt 0.2.5 | NEW whether to use typeit animation for title name
      typeit = false
    # FixIt 0.2.12 | NEW Header subtitle config
    [params.header.subtitle]
      # subtitle name
      name = ""
      # whether to use typeit animation for subtitle name
      typeit = true
[params.home]
    # FixIt 0.2.0 | NEW amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      #gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "/images/avatar.png"
      # FixIt 0.2.17 | NEW identifier of avatar menu link
      avatarMenu = ""
      # FixIt 0.2.7 | CHANGED title shown in home page (HTML format is supported)
      title = ""
      # subtitle shown in home page
      subtitle = "On my way to Pala for 1 year jailtime"
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
      # FixIt 0.2.0 | NEW disclaimer (HTML format is supported)
      disclaimer = ""
    [params.search]
    enable = true
    # type of search engine ["lunr", "algolia", "fuse"]
    type = "lunr"
    # max index length of the chunked content
    contentLength = 4000
    # placeholder of the search bar
    placeholder = ""
    # FixIt 0.2.1 | NEW max number of results length
    maxResultLength = 10
    # FixIt 0.2.3 | NEW snippet length of the result
    snippetLength = 30
    # FixIt 0.2.1 | NEW HTML tag name of the highlight part in results
    highlightTag = "em"
    # FixIt 0.2.4 | NEW whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/hugo-fixit/FixIt/issues/43)
    noClasses = false
